server:
  port: 8082
spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS